name: sophia_path
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  path: ^1.8.0
  provider: ^6.0.0
  sqflite_common_ffi: ^2.4.0+1
  intl: ^0.20.2
  shared_preferences: ^2.5.4
  image_picker: ^1.2.1
  sqflite_common_ffi_web: ^1.1.1
  share_plus: ^12.0.1
  google_fonts: ^8.0.0
  curved_navigation_bar: ^1.0.6
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
